version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - .:/opt/
    ports:
      - '9000:9000'
    depends_on:
      - db
      - nginx

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./static:/opt/static
    ports:
      - '8080:80'

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - '3306:3306'
